<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Vika
 * Date: 03.06.12
 * Time: 12:28
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>John Conway's Game of Life</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="Cache-Control" content="no-cache"/>
    <meta http-equiv="Pragma" content="no-cache" />
    <link href="css/style.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="js/life.js"></script>
</head>
<body>
<h1>John Conway's Game of Life</h1>

<div id="fMain">
<?php
include $template;
?>
</div>

&#169; 2012, Vika Tskhay
</body>
</html>